# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# GitHub Actions for Azure: https://github.com/Azure/actions

# Workflow name (visible in GitHub Actions UI)
name: Build and deploy Python app to Azure Web App - studentssperformance3

# Trigger configuration
on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch
  workflow_dispatch:  # Allow manual triggering via GitHub UI

# Jobs define the workflow steps
jobs:
  build:
    runs-on: ubuntu-latest  # Use GitHub-hosted Ubuntu runner

    steps:
      # Step 1: Check out the repository code
      - uses: actions/checkout@v2  # Required to access the code

      # Step 2: Set up Python 3.7
      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'  # Specify Python version (match your app's requirements)

      # Step 3: Create a virtual environment
      - name: Create and start virtual environment
        run: |
          python -m venv venv  # Create a virtual environment
          source venv/bin/activate  # Activate it (optional, but useful for dependency isolation)

      # Step 4: Install dependencies from requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt  # Install project dependencies

      # Step 5: Upload artifact for deployment (exclude virtual environment)
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app  # Artifact name
          path: |  # Include all files except 'venv/'
            . 
            !venv/

  # Deploy job runs after successful build
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Depends on the 'build' job
    environment:
      name: 'Production'  # GitHub environment (enables deployment protections)
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}  # Azure Web App URL

    steps:
      # Step 1: Download the artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app  # Matches the uploaded artifact name
          path: .  # Save to the current directory

      # Step 2: Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp  # ID for referencing outputs
        with:
          app-name: 'studentssperformance3'  # Azure Web App name
          slot-name: 'Production'  # Deployment slot (use 'Production' for default)
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DA91177C75E346B4BD3AD2EF1D318517 }}  # Azure credentials from GitHub Secrets